# Generated by Django 2.2 on 2019-04-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dueDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
