# Generated by Django 2.2 on 2019-04-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20190426_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dueDate',
            field=models.DateField(blank=True, choices=[('In Progress', 'In Progress'), ('To Do', 'To Do'), ('Done', 'Done')], max_length=20),
        ),
    ]
