# Generated by Django 2.2 on 2019-04-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20190428_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dueDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('To Do', 'To Do'), ('Done', 'Done')], default='To Do', max_length=100),
        ),
    ]
