# Generated by Django 2.2 on 2019-04-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20190428_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='To Do', max_length=100),
        ),
    ]
